dataset:
  val:
  - name: nyu_v2
    disp_name: nyu_train_full
    dir: nyuv2/nyu_labeled_extracted.tar
    filenames: data_split/nyu/labeled/filename_list_test.txt
    eigen_valid_mask: true
  - name: kitti
    disp_name: kitti_eigen_test_full
    dir: kitti/kitti_eigen_split_test.tar
    filenames: data_split/kitti/eigen_test_files_with_gt.txt
    kitti_bm_crop: true
    valid_mask_crop: eigen
  # - name: diode
  #   disp_name: diode_val_all
  #   dir: diode/diode_val.tar
  #   filenames: data_split/diode/diode_val_all_filename_list.txt 